import java.io.FileWriter;
import java.io.IOException;
import java.io.Writer;

import net.tinyos.message.*;
import net.tinyos.util.*;

/**
 * 
 * Class responsible for sending packages to the SerialForwarder
 * It sends only Packages of type DdcForecastMsg (see DdcForecastMsg.java), which is a file
 * generated by tinyOS based on the specification of the header
 * 
 * @author anh tuan nguyen
 * 
 */
public class Communication implements MessageListener {
	MoteIF mote;
	String fileName;

	public void init() {
		mote = new MoteIF(PrintStreamMessenger.err);
	}
	public Communication(){
		//unused
	}
	
    public Communication(boolean testMode,String fileName){
    	if(testMode){
    		this.fileName =fileName;
    		mote = new MoteIF(PrintStreamMessenger.err);
    		mote.registerListener(new DdcTestMsg(), this);
    	}
		
	}
    public void destroy(){
    	mote.getSource().shutdown();
    }
	/* Send RadioPaket. */
	
	void sendPackage(short[] data, byte sunset, byte sunrise, byte resolution, byte numberOfDays){
		DdcForecastMsg msg = new DdcForecastMsg(4 + data.length); // 4 is the header length and the rest is payload length
		msg.set_data(data);
		msg.set_header_sunset(sunset);
		msg.set_header_sunrise(sunrise);
		msg.set_header_resolution(resolution);
		msg.set_header_numDays(numberOfDays);
		try {
			mote.send(MoteIF.TOS_BCAST_ADDR, msg);
		} catch (IOException e) {
			System.out.println("Nachricht kann nicht gesendet werden");
		}
		
	}


	/**
	 * methods for receiving packages 
	 * not working currently
	 */
	public void messageReceived(int arg0, Message arg1) {
		DdcTestMsg msg = (DdcTestMsg)arg1;
		String tmp = "";
		for(int i= 0; i< msg.get_numValues(); i++){
			tmp+=msg.getElement_values(i)+"*";
		}
		tmp+=msg.get_decodingTime();
		System.out.println(tmp);
		System.out.println(msg.get_numValues());
		
		Writer fw = null;
		// Write data into file 	
		try {
			fw = new FileWriter(fileName, true);

			fw.write(tmp);
			fw.append(System.getProperty("line.separator")); // neue zeile

		} catch (IOException e) {
			System.out.println("Fehler beim schreiben");
		} finally {
			if (fw != null)
				try {
					fw.close();
				} catch (IOException e) {
					e.printStackTrace();
				}

		}
		
			
	}

}
