/**
 * This class is automatically generated by mig. DO NOT EDIT THIS FILE.
 * This class implements a Java interface to the 'DdcTestMsg'
 * message type.
 */

public class DdcTestMsg extends net.tinyos.message.Message {

    /** The default size of this message type in bytes. */
    public static final int DEFAULT_MESSAGE_SIZE = 79;

    /** The Active Message type associated with this message. */
    public static final int AM_TYPE = 123;

    /** Create a new DdcTestMsg of size 79. */
    public DdcTestMsg() {
        super(DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /** Create a new DdcTestMsg of the given data_length. */
    public DdcTestMsg(int data_length) {
        super(data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new DdcTestMsg with the given data_length
     * and base offset.
     */
    public DdcTestMsg(int data_length, int base_offset) {
        super(data_length, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new DdcTestMsg using the given byte array
     * as backing store.
     */
    public DdcTestMsg(byte[] data) {
        super(data);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new DdcTestMsg using the given byte array
     * as backing store, with the given base offset.
     */
    public DdcTestMsg(byte[] data, int base_offset) {
        super(data, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new DdcTestMsg using the given byte array
     * as backing store, with the given base offset and data length.
     */
    public DdcTestMsg(byte[] data, int base_offset, int data_length) {
        super(data, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new DdcTestMsg embedded in the given message
     * at the given base offset.
     */
    public DdcTestMsg(net.tinyos.message.Message msg, int base_offset) {
        super(msg, base_offset, DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new DdcTestMsg embedded in the given message
     * at the given base offset and length.
     */
    public DdcTestMsg(net.tinyos.message.Message msg, int base_offset, int data_length) {
        super(msg, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
    /* Return a String representation of this message. Includes the
     * message type name and the non-indexed field values.
     */
    public String toString() {
      String s = "Message <DdcTestMsg> \n";
      try {
        s += "  [decodingTime=0x"+Long.toHexString(get_decodingTime())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [numValues=0x"+Long.toHexString(get_numValues())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [sunrise=0x"+Long.toHexString(get_sunrise())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [sunset=0x"+Long.toHexString(get_sunset())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [values=";
        for (int i = 0; i < 72; i++) {
          s += "0x"+Long.toHexString(getElement_values(i) & 0xff)+" ";
        }
        s += "]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      return s;
    }

    // Message-type-specific access methods appear below.

    /////////////////////////////////////////////////////////
    // Accessor methods for field: decodingTime
    //   Field type: long, unsigned
    //   Offset (bits): 0
    //   Size (bits): 32
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'decodingTime' is signed (false).
     */
    public static boolean isSigned_decodingTime() {
        return false;
    }

    /**
     * Return whether the field 'decodingTime' is an array (false).
     */
    public static boolean isArray_decodingTime() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'decodingTime'
     */
    public static int offset_decodingTime() {
        return (0 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'decodingTime'
     */
    public static int offsetBits_decodingTime() {
        return 0;
    }

    /**
     * Return the value (as a long) of the field 'decodingTime'
     */
    public long get_decodingTime() {
        return (long)getUIntBEElement(offsetBits_decodingTime(), 32);
    }

    /**
     * Set the value of the field 'decodingTime'
     */
    public void set_decodingTime(long value) {
        setUIntBEElement(offsetBits_decodingTime(), 32, value);
    }

    /**
     * Return the size, in bytes, of the field 'decodingTime'
     */
    public static int size_decodingTime() {
        return (32 / 8);
    }

    /**
     * Return the size, in bits, of the field 'decodingTime'
     */
    public static int sizeBits_decodingTime() {
        return 32;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: numValues
    //   Field type: short, unsigned
    //   Offset (bits): 32
    //   Size (bits): 8
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'numValues' is signed (false).
     */
    public static boolean isSigned_numValues() {
        return false;
    }

    /**
     * Return whether the field 'numValues' is an array (false).
     */
    public static boolean isArray_numValues() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'numValues'
     */
    public static int offset_numValues() {
        return (32 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'numValues'
     */
    public static int offsetBits_numValues() {
        return 32;
    }

    /**
     * Return the value (as a short) of the field 'numValues'
     */
    public short get_numValues() {
        return (short)getUIntBEElement(offsetBits_numValues(), 8);
    }

    /**
     * Set the value of the field 'numValues'
     */
    public void set_numValues(short value) {
        setUIntBEElement(offsetBits_numValues(), 8, value);
    }

    /**
     * Return the size, in bytes, of the field 'numValues'
     */
    public static int size_numValues() {
        return (8 / 8);
    }

    /**
     * Return the size, in bits, of the field 'numValues'
     */
    public static int sizeBits_numValues() {
        return 8;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: sunrise
    //   Field type: short, unsigned
    //   Offset (bits): 40
    //   Size (bits): 8
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'sunrise' is signed (false).
     */
    public static boolean isSigned_sunrise() {
        return false;
    }

    /**
     * Return whether the field 'sunrise' is an array (false).
     */
    public static boolean isArray_sunrise() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'sunrise'
     */
    public static int offset_sunrise() {
        return (40 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'sunrise'
     */
    public static int offsetBits_sunrise() {
        return 40;
    }

    /**
     * Return the value (as a short) of the field 'sunrise'
     */
    public short get_sunrise() {
        return (short)getUIntBEElement(offsetBits_sunrise(), 8);
    }

    /**
     * Set the value of the field 'sunrise'
     */
    public void set_sunrise(short value) {
        setUIntBEElement(offsetBits_sunrise(), 8, value);
    }

    /**
     * Return the size, in bytes, of the field 'sunrise'
     */
    public static int size_sunrise() {
        return (8 / 8);
    }

    /**
     * Return the size, in bits, of the field 'sunrise'
     */
    public static int sizeBits_sunrise() {
        return 8;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: sunset
    //   Field type: short, unsigned
    //   Offset (bits): 48
    //   Size (bits): 8
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'sunset' is signed (false).
     */
    public static boolean isSigned_sunset() {
        return false;
    }

    /**
     * Return whether the field 'sunset' is an array (false).
     */
    public static boolean isArray_sunset() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'sunset'
     */
    public static int offset_sunset() {
        return (48 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'sunset'
     */
    public static int offsetBits_sunset() {
        return 48;
    }

    /**
     * Return the value (as a short) of the field 'sunset'
     */
    public short get_sunset() {
        return (short)getUIntBEElement(offsetBits_sunset(), 8);
    }

    /**
     * Set the value of the field 'sunset'
     */
    public void set_sunset(short value) {
        setUIntBEElement(offsetBits_sunset(), 8, value);
    }

    /**
     * Return the size, in bytes, of the field 'sunset'
     */
    public static int size_sunset() {
        return (8 / 8);
    }

    /**
     * Return the size, in bits, of the field 'sunset'
     */
    public static int sizeBits_sunset() {
        return 8;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: values
    //   Field type: short[], unsigned
    //   Offset (bits): 56
    //   Size of each element (bits): 8
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'values' is signed (false).
     */
    public static boolean isSigned_values() {
        return false;
    }

    /**
     * Return whether the field 'values' is an array (true).
     */
    public static boolean isArray_values() {
        return true;
    }

    /**
     * Return the offset (in bytes) of the field 'values'
     */
    public static int offset_values(int index1) {
        int offset = 56;
        if (index1 < 0 || index1 >= 72) throw new ArrayIndexOutOfBoundsException();
        offset += 0 + index1 * 8;
        return (offset / 8);
    }

    /**
     * Return the offset (in bits) of the field 'values'
     */
    public static int offsetBits_values(int index1) {
        int offset = 56;
        if (index1 < 0 || index1 >= 72) throw new ArrayIndexOutOfBoundsException();
        offset += 0 + index1 * 8;
        return offset;
    }

    /**
     * Return the entire array 'values' as a short[]
     */
    public short[] get_values() {
        short[] tmp = new short[72];
        for (int index0 = 0; index0 < numElements_values(0); index0++) {
            tmp[index0] = getElement_values(index0);
        }
        return tmp;
    }

    /**
     * Set the contents of the array 'values' from the given short[]
     */
    public void set_values(short[] value) {
        for (int index0 = 0; index0 < value.length; index0++) {
            setElement_values(index0, value[index0]);
        }
    }

    /**
     * Return an element (as a short) of the array 'values'
     */
    public short getElement_values(int index1) {
        return (short)getUIntBEElement(offsetBits_values(index1), 8);
    }

    /**
     * Set an element of the array 'values'
     */
    public void setElement_values(int index1, short value) {
        setUIntBEElement(offsetBits_values(index1), 8, value);
    }

    /**
     * Return the total size, in bytes, of the array 'values'
     */
    public static int totalSize_values() {
        return (576 / 8);
    }

    /**
     * Return the total size, in bits, of the array 'values'
     */
    public static int totalSizeBits_values() {
        return 576;
    }

    /**
     * Return the size, in bytes, of each element of the array 'values'
     */
    public static int elementSize_values() {
        return (8 / 8);
    }

    /**
     * Return the size, in bits, of each element of the array 'values'
     */
    public static int elementSizeBits_values() {
        return 8;
    }

    /**
     * Return the number of dimensions in the array 'values'
     */
    public static int numDimensions_values() {
        return 1;
    }

    /**
     * Return the number of elements in the array 'values'
     */
    public static int numElements_values() {
        return 72;
    }

    /**
     * Return the number of elements in the array 'values'
     * for the given dimension.
     */
    public static int numElements_values(int dimension) {
      int array_dims[] = { 72,  };
        if (dimension < 0 || dimension >= 1) throw new ArrayIndexOutOfBoundsException();
        if (array_dims[dimension] == 0) throw new IllegalArgumentException("Array dimension "+dimension+" has unknown size");
        return array_dims[dimension];
    }

    /**
     * Fill in the array 'values' with a String
     */
    public void setString_values(String s) { 
         int len = s.length();
         int i;
         for (i = 0; i < len; i++) {
             setElement_values(i, (short)s.charAt(i));
         }
         setElement_values(i, (short)0); //null terminate
    }

    /**
     * Read the array 'values' as a String
     */
    public String getString_values() { 
         char carr[] = new char[Math.min(net.tinyos.message.Message.MAX_CONVERTED_STRING_LENGTH,72)];
         int i;
         for (i = 0; i < carr.length; i++) {
             if ((char)getElement_values(i) == (char)0) break;
             carr[i] = (char)getElement_values(i);
         }
         return new String(carr,0,i);
    }

}
