/**
 * This class is automatically generated by mig. DO NOT EDIT THIS FILE.
 * This class implements a Java interface to the 'SinkAck'
 * message type.
 */

public class SinkAck extends net.tinyos.message.Message {

    /** The default size of this message type in bytes. */
    public static final int DEFAULT_MESSAGE_SIZE = 2;

    /** The Active Message type associated with this message. */
    public static final int AM_TYPE = 67;

    /** Create a new SinkAck of size 2. */
    public SinkAck() {
        super(DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /** Create a new SinkAck of the given data_length. */
    public SinkAck(int data_length) {
        super(data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new SinkAck with the given data_length
     * and base offset.
     */
    public SinkAck(int data_length, int base_offset) {
        super(data_length, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new SinkAck using the given byte array
     * as backing store.
     */
    public SinkAck(byte[] data) {
        super(data);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new SinkAck using the given byte array
     * as backing store, with the given base offset.
     */
    public SinkAck(byte[] data, int base_offset) {
        super(data, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new SinkAck using the given byte array
     * as backing store, with the given base offset and data length.
     */
    public SinkAck(byte[] data, int base_offset, int data_length) {
        super(data, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new SinkAck embedded in the given message
     * at the given base offset.
     */
    public SinkAck(net.tinyos.message.Message msg, int base_offset) {
        super(msg, base_offset, DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new SinkAck embedded in the given message
     * at the given base offset and length.
     */
    public SinkAck(net.tinyos.message.Message msg, int base_offset, int data_length) {
        super(msg, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
    /* Return a String representation of this message. Includes the
     * message type name and the non-indexed field values.
     */
    public String toString() {
      String s = "Message <SinkAck> \n";
      try {
        s += "  [nodeId=0x"+Long.toHexString(get_nodeId())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [seqNr=0x"+Long.toHexString(get_seqNr())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      return s;
    }

    // Message-type-specific access methods appear below.

    /////////////////////////////////////////////////////////
    // Accessor methods for field: nodeId
    //   Field type: short, unsigned
    //   Offset (bits): 0
    //   Size (bits): 8
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'nodeId' is signed (false).
     */
    public static boolean isSigned_nodeId() {
        return false;
    }

    /**
     * Return whether the field 'nodeId' is an array (false).
     */
    public static boolean isArray_nodeId() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'nodeId'
     */
    public static int offset_nodeId() {
        return (0 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'nodeId'
     */
    public static int offsetBits_nodeId() {
        return 0;
    }

    /**
     * Return the value (as a short) of the field 'nodeId'
     */
    public short get_nodeId() {
        return (short)getUIntBEElement(offsetBits_nodeId(), 8);
    }

    /**
     * Set the value of the field 'nodeId'
     */
    public void set_nodeId(short value) {
        setUIntBEElement(offsetBits_nodeId(), 8, value);
    }

    /**
     * Return the size, in bytes, of the field 'nodeId'
     */
    public static int size_nodeId() {
        return (8 / 8);
    }

    /**
     * Return the size, in bits, of the field 'nodeId'
     */
    public static int sizeBits_nodeId() {
        return 8;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: seqNr
    //   Field type: short, unsigned
    //   Offset (bits): 8
    //   Size (bits): 8
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'seqNr' is signed (false).
     */
    public static boolean isSigned_seqNr() {
        return false;
    }

    /**
     * Return whether the field 'seqNr' is an array (false).
     */
    public static boolean isArray_seqNr() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'seqNr'
     */
    public static int offset_seqNr() {
        return (8 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'seqNr'
     */
    public static int offsetBits_seqNr() {
        return 8;
    }

    /**
     * Return the value (as a short) of the field 'seqNr'
     */
    public short get_seqNr() {
        return (short)getUIntBEElement(offsetBits_seqNr(), 8);
    }

    /**
     * Set the value of the field 'seqNr'
     */
    public void set_seqNr(short value) {
        setUIntBEElement(offsetBits_seqNr(), 8, value);
    }

    /**
     * Return the size, in bytes, of the field 'seqNr'
     */
    public static int size_seqNr() {
        return (8 / 8);
    }

    /**
     * Return the size, in bits, of the field 'seqNr'
     */
    public static int sizeBits_seqNr() {
        return 8;
    }

}
